language: python
python:
  - 3.4
  - 3.5

sudo: false

addons:
  apt:
    install:
      - wine
      - wine32
      - wine64

before_install:
  - pip install -r test-requirements.txt
  - pip install codecov

script:
  - py.test --cov-config=.coveragerc redll

after_success:
  - codecov
