skip_tags: true
clone_depth: 1

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -r test-requirements.txt"
  - "pip install codecov"

test_script:
  - py.test -ra --cov=machomachomangler --cov-config=.coveragerc machomachomangler
  - codecov
